### ISSUE TITLE
Vim Extra Tips

### ISSUE THREAD

**Issue by Kjuly** [Kjuly/issues#19]
### Multiple replace:

`^v` -> choose vertically -> `s` -> input target (e.g.:`:`) -> `esc`.

I:

```
a aaa
b bbb
c ccc
```

O:

```
a:aaa
b:bbb
c:ccc
```

**Comment by zzz6519003** [comment]
don't tell me you use vim for ios dev

**Comment by Kjuly** [comment]
@zzz6519003 nope, I use Xcode. Sometimes will use Vim as a tool to do some batch jobs. ;)
