### ISSUE TITLE
UITableViewCell show white background and cannot be modified on iOS 7

### ISSUE THREAD

**Issue by Kjuly** [Kjuly/issues#22]
I've implemented a custom table view cell class that inherit from `UITableViewCell`. The tableview contains a background image, so I want cell's background to be transparent. It looks great before iOS7.

However, in iOS7, the cell is always shown with a white background.

**Comment by Kjuly** [comment]
As Apple DOC said (UITableViewCell Class Reference):

> ... **In iOS 7, cells have a white background by default**; in earlier versions of iOS, cells inherit the background color of the enclosing table view. If you want to change the background color of a cell, do so in the **_tableView:willDisplayCell:forRowAtIndexPath:**_ method of your table view delegate.

So for my case that to show cells with transparent background, just need to implement the delegate method in the table view controller like below:

```
- (void)tableView:(UITableView *)tableView
  willDisplayCell:(UITableViewCell *)cell
forRowAtIndexPath:(NSIndexPath *)indexPath
{
  [cell setBackgroundColor:[UIColor clearColor]];
}
```

**Comment by Kjuly** [comment]
Thread on SO: ["UITableViewCell show white background and cannot be modified on iOS7"](http://stackoverflow.com/questions/18878258/uitableviewcell-show-white-background-and-cannot-be-modified-on-ios7).

**Comment by zzz6519003** [comment]
"It looks great" I wonder how it looks lol

**Comment by Kjuly** [comment]
@zzz6519003 ಠ_ಠ
