### ISSUE TITLE
How to set status bar's content color to white on iOS 7

### ISSUE THREAD

**Issue by Kjuly** [Kjuly/issues#23]
My App’s background colour is black. Cause the whole view is below the status bar on iOS 7, the content on the status bar will hard to be distinguished. So how to change status bar’s content colour to white?

**Comment by Kjuly** [comment]
1. Set "View controller-based status bar appearance” to **NO** in your **info.list** file;
2. Insert
   
   ```
   [[UIApplication sharedApplication] setStatusBarStyle:UIStatusBarStyleLightContent];
   ```
   
   to `-application:didFinishLaunchingWithOptions:` of the AppDelegate.m.

---

**Note**: `UIStatusBarStyleDefault` is the default value for the status bar style, it'll show black content instead. Both `UIStatusBarStyleBlackTranslucent` & `UIStatusBarStyleBlackOpaque` are deprecated in iOS 7.0.

**Comment by Kjuly** [comment]
Thread on SO: ["How to set status bar's content color to white on iOS 7"](http://stackoverflow.com/questions/18953879/how-to-set-status-bars-content-color-to-white-on-ios-7).

**Comment by zzz6519003** [comment]
这玩意做博客很天才啊，我开始还觉得不以为然。。。

**Comment by Kjuly** [comment]
@zzz6519003 已经有先例了 也有用gist来写的 ;)

**Comment by zzz6519003** [comment]
gist没有绿色不幸福~.~

**Comment by DWFLZXJ** [comment]
厉害了我的哥
