### ISSUE TITLE
FXBlurView: Undefined symbols for architecture armv7 _vImageBoxConvolve_ARGB8888

### ISSUE THREAD

**Issue by Kjuly** [Kjuly/issues#25]
Solution: Just add `Accelerate.framework`.

---

Way to figure out which framework is needed:

Search `_vImageBoxConvolve_ARGB8888` by <kbd>Shift</kbd> <kbd>Cmd</kbd> <kbd>o</kbd>.

**Comment by itrunks** [comment]
mash up. thanks. but i need to know why it need for ios 7.1. becasue same i worked in ios 7.0 it doesn't required that frameworks. why it need for ios 7.1 explain please

**Comment by Kjuly** [comment]
@iDevAndroid sorry, not totally sure about your case, it varies according to your project's dependence. Like FXBlurView lib, it requires this framework. I got this issue on iOS 7.0.

**Comment by itrunks** [comment]
Thanks for your reply but i got issue only iOS 7.1 and one more issue the background patten image is different up on the version iOS 6,7.0 and 7.1
