### ISSUE TITLE
Cannot present a view controller modally from an action sheet's delegate in iOS 8

### ISSUE THREAD

**Issue by Kjuly** [Kjuly/issues#27]
Try to do your job (presenting view controller) in

```
- (void)      actionSheet:(UIActionSheet *)actionSheet
didDismissWithButtonIndex:(NSInteger)buttonIndex {}
```

instead of

```
- (void) actionSheet:(UIActionSheet *)actionSheet
clickedButtonAtIndex:(NSInteger)buttonIndex {}
```

_"The problem seems to come from Apple's switch to using UIAlertController internally to implement the functionality of alert views and action sheets"_. So you must to wait the action sheet dismissed, then present the view controller you want.

And another solution:

```
dispatch_async(dispatch_get_main_queue(), ^ {
    [self presentViewController:viewController animated:YES completion:nil];
});
```

it'll just block the UI at main thread, so it'll also make sure the view controller will be presented after the action sheet was dismissed.

---
### Reference

http://stackoverflow.com/questions/24854802/presenting-a-view-controller-modally-from-an-action-sheets-delegate-in-ios8

**Comment by zzz6519003** [comment]
web大法好
