### ISSUE TITLE
#download-youtobe-video(720p/1080p)

### ISSUE THREAD

**Issue by qingsong-hub** [Kjuly/issues#37]
Windows PowerShell
版权所有 (C) 2009 Microsoft Corporation。保留所有权利。

PS C:\Users\Administrator> cd C:\Users\Administrator\Desktop
PS C:\Users\Administrator\Desktop> you-get -k https://www.youtube.com/watch?v=jpmu6u24MNo
site:                YouTube
title:               阿滴英文砸招牌! 同步翻譯議會質詢超崩潰!? feat. 浩爾
stream:
    - itag:          313
      container:     webm
      quality:       3840x2160 (2160p)
      size:          1448.6 MiB (1519002480 bytes)
    # download-with: you-get --itag=313 [URL]

Downloading 阿滴英文砸招牌! 同步翻譯議會質詢超崩潰!- feat. 浩爾.webm ...
 0.0% (   0.0/1448.6MB) ├──────────────────────────────────────┤[1/2] you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.
PS C:\Users\Administrator\Desktop>

**Comment by Kjuly** [comment]
Sorry, please report your issue to the author of [you-get](https://github.com/soimort/you-get).

Btw, I guess your error might related to proxy settings, you can take a look at https://github.com/soimort/you-get#proxy-settings
