### ISSUE TITLE
Fc4  baseline experiment log

### ISSUE THREAD

**Issue by Jing-XING** [Kjuly/issues#44]
First run:
Loss:  Folder2, 1, 0: 1.52, 1.72,1.50
// loss is not equal to Fc4, so run second time
Second run:
Loss: Folder2, 1, 0: 1.54, 1.72, 1.48
// same as first run, check the code

**Comment by Jing-XING** [comment]
find the loss goes down with increasing epochs,
epochs mean_loss
2000 1.69
3000 1.61
4000 1.58

**Comment by Jing-XING** [comment]
epoch=6000, batchize=16
2000 1.69
3000 1.61
4000 1.59
6000 1.55
\\todo add more epochs

**Comment by Jing-XING** [comment]
6000 more epochs 1.52, and still going up

**Comment by Kjuly** [comment]
Hi @Jing-XING , please create ur own repo and leave ur logs there. I'll close this issue, sorry.

**Comment by Jing-XING** [comment]
@Kjuly Hi, Sorry I didn't realized this issue is in you place, you can delete it.

**Comment by Kjuly** [comment]
@Jing-XING haha, it's ok, just leave it closed, seems no way to do deletion.

**Comment by jiehucn** [comment]
> First run: Loss: Folder2, 1, 0: 1.52, 1.72,1.50 // loss is not equal to Fc4, so run second time Second run: Loss: Folder2, 1, 0: 1.54, 1.72, 1.48 // same as first run, check the code

what that mean?

**Comment by Jing-XING** [comment]
> @Jing-XING haha, it's ok, just leave it closed, seems no way to do deletion.

Could you try the  'Delete issuse' on the bottom of right hand colum? 
Cause people start ask me questions about this issue...
